### ISSUE TITLE
FF causes a loop for the plugin

### ISSUE THREAD

**Issue by amir36** [readybytes/JoomlaXi-Redirect-To-Edit-Profile#6]
Hi,

I am using Payplans and Jomsocial 3.2.1.1; the recent versions of FF has been causing the very useful 'Redirect-To-Edit-Profile' plugin to stop functioning and create some kind of redundant loop.

Since the error is caused by FF, and we do not have any control over it. Knowing the fact how popular FF is, we cannot ignore it either. Therefore, can we please make certain changes to the plugin code so that it would automatically empty the cache or do whatever is necessary to rectify the problem?

Thank you very much,
Amir

**Comment by rbsl-shakuntala** [comment]
Fixed in Redirect to Edit Profile 2.5
