### ISSUE TITLE
JSPT Redirect Option in Backend

### ISSUE THREAD

**Issue by testcouch** [readybytes/JoomlaXi-Redirect-To-Edit-Profile#7]
i'm using Payplans, JSPT and Jomsocial 3.2.1.5 together with the very useful 'Redirect-To-Edit-Profile' plugin. But the Redirect works for every JSPT Profiletypes and that's cause a issue with Quick Registration App from Payplans. The Redirect Plugin need a additional Backend Setting that allow to define wich Profiletype should be Redirect to Edit Profile and wich not! Here are the First Code for RediretToEditProfile.xml File

[code]<fields name="params">
		<fieldset name="basic">
		<field name="profiletype" type="text" default="" label="XIPT Profile ID" description="Enter a XIPT Profile Type ID to apply redirect only for specific ID. If you want to add more than one than Add Comma(i.e. 1,2,5 etc) seperated ID's." />
			<field name="whenredirect" type="radio" default="0" label="When to redirect user" description="Select 'Just After login' when you want to redirect only after login else select 'Everytime'.">
				<option value="1">Everytime</option>
				<option value="0">Just After Login</option>
			</field>[/code]

**Comment by rbsl-shakuntala** [comment]
Fixed in Redirect to Edit Profile 2.5
