### ISSUE TITLE
Facebook Connect not work with Redirect and JSPT Force to Upload Avatar

### ISSUE THREAD

**Issue by testcouch** [readybytes/JoomlaXi-Redirect-To-Edit-Profile#8]
Facebook Connect Login does not work if User forced to UploadAvatar Rule and RedirectToEdit Profile plugin is enabled. i get Too ManyRedirectsError (blankPage) or User is not redirected to Profile Edit!

Here are the Scenario i'v tested:

1. upload avatar Rule (enabled) + RedirectToEditProfile (enabled) = Too Many Redirects Error and Blank Page

2. upload avatar Rule (disabled) + RedirectToEditProfile (enabled) = Too Many Redirects Error gone but FB User is still not Redirect from FB Popup to Profile after register

3. upload avatar Rule (disabled) + RedirectToEditProfile (disabled) = Everything works as expected

Settings Backend:

- ACL Rule Force to Upload Avatar (Yes)

- ACL Rule = Force Redirection during Ajax Request -> (No)

- Jomsocial setting FB Connect = Automatically Re-Import User Avatar Upon Each Login -> (Yes)

Setting Frontend:

- FB Login Popup = Reimport Avatar (yes)

**Comment by rbsl-shakuntala** [comment]
Fixed in Redirect to Edit Profile 2.5
